### ISSUE TITLE
script will never match

### ISSUE THREAD

**Issue by bahbarnett** [LongWayHomie/Plutus-dogecoin#5]
You have a few bugs in this script, but this one is the most key.  The script will never match, because you create a set inside of a list.

This:

    database = [set(line.strip() for line in open ('database/dormant_list'))]

Should be this:

    database = set(line.strip() for line in open ('database/dormant_list'))

**Comment by LongWayHomie** [comment]
You're correct. I should correct code shortly. Thanks!
